### ISSUE TITLE
There was a temporary problem while delivering your message to XXX@XXX.COM. 

### ISSUE THREAD

**Issue by kmswong888** [crisp-oss/email-bounce-parser#2]
For Google, they would also use the below sentence:

"There was a temporary problem while delivering your message to XXX@XXX.COM. Gmail will retry for 47 more hours. You'll be notified if the delivery fails permanently."

Note the "While" in 'While delivering your message".  In your parser, you only included the sentence without "WHILE".

**Comment by eliottvincent** [comment]
I somewhat missed this issue, sorry for the delay! This is fixed in version [1.0.22](https://github.com/crisp-oss/email-bounce-parser/releases/tag/v1.0.22)
